server:
  port: 8081
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://192.168.25.130:3306/mydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
            url: jdbc:mysql://192.168.25.130:3306/mysql?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
            username: root
            password: root
            driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2